name: emuchull
description: "Aplicación de escritorio en Flutter para gestionar emuladores y juegos."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  file_picker: ^10.3.3
  path_provider: ^2.1.4
  screen_retriever: ^0.2.0
  window_manager: ^0.5.1
  video_player: ^2.5.0
  dart_vlc: ^0.4.0
  audio_video_progress_bar: ^0.11.0

  win32: ^5.5.0
  win32_gamepad: ^1.0.9
  audioplayers: ^6.5.1
 

  crypto: ^3.0.3
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.11.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/avatars/
    - assets/sounds/nav.wav
    - assets/sounds/action.wav
    - assets/sounds/launch.wav
    - assets/sounds/bg_menu.mp3
    - assets/videos/login.mp4

flutter_icons:
  android: false
  ios: false
  image_path: "assets/icons/Emuchull.png"
  windows: true
  web: false
